### ISSUE TITLE
create a parent class for BaseSimulation

### ISSUE THREAD

**Issue by minsikl** [IBM/spacetech-kubesat#6]
- create BaseService class as a parent class of BaseSimulation. 
- remove simulation_timepulse callback from BaseService class
- remove initialize.service request from run function
- change BaseSimulation class as a child class

**Comment by Jordy24** [comment]
How do you suggest to go about on BaseService class, like what needs to be in there?..
And also the "simulation_timepulse" is just a topic/subject name so its not tied in anyway with BaseSimulation module..
Or could you please explain more on the BaseService class.

**Comment by minsikl** [comment]
simulation.timestamp callback is a simulation specific callback. So, it will be removed. 
node.status callback is useful to check the service status and can be used other than the simulation cases.
Other functions will be kept in the BaseService.

**Comment by minsikl** [comment]
PR #18 has been merged
